### ISSUE TITLE
ci files...

### ISSUE THREAD

**Issue by andymaheshw** [andymaheshw/pyamc#17]
Hey Randy, 

What are the ci files? Sorry to bug you about it. Thanks!

**Comment by randyzwitch** [comment]
`ci` in this case is referring to Continuous Integration, the practice of merging code into a central repository to make sure that it always builds. That's what the Travis and Appveyor systems are for.

For this repository, these were also auto-generated by the script I used to make the Python package valid. I believe one of the files is used by Travis, but I'm not sure which one off-hand. An area to clean up later on down the road.

**Comment by andymaheshw** [comment]
How did you set the environment variables for travis?

**Comment by andymaheshw** [comment]
Encrypting environment variables #

Encrypt environment variables with the public key attached to your repository using the travis gem:

If you do not have the travis gem installed, run gem install travis.

In your repository directory, run:

travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
Commit the changes to your .travis.yml.

**Comment by randyzwitch** [comment]
Yes, I already did the Travis side, I'd have to read how to do it for AppVeyor
