### ISSUE TITLE
Decide on package name

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/pyamc#21]
pyadobemc not the greatest name, just used it to disambiguate the `from adobeanalytics import AdobeAnalytics` issues I was encountering.

Surprisingly, pyamc doesn't appear to be used by anyone (amc = Adobe Marketing Cloud).

Suggestions?

**Comment by andymaheshw** [comment]
sounds great.

**Comment by randyzwitch** [comment]
Cool. pyamc it is. Do you want to update the Python references or do you want me to?

**Comment by andymaheshw** [comment]
I got it.

**Comment by randyzwitch** [comment]
You should change the repo name too, so when people type pyamc the repo and documentation will be labeled that too. Don't worry about the message that it's dangerous, it's not a problem (since no one links to this yet). At worst, you'll need to re-download the repo for development again, since the .git configuration files will change

**Comment by andymaheshw** [comment]
renamed the repo, and everything seems ok...also setup.py is up to date with the change...anything else?
