### ISSUE TITLE
Make AppVeyor work (Windows)

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/pyamc#23]

**Comment by andymaheshw** [comment]
Cool, so I ran appveyor (but it failed a bunch.. haha)
This line seems to be the cause...py.test must have different params?

 ERROR: InvocationError: 'C:\\projects\\adobeanalytics\\.tox\\py34\\Scripts\\py.test.EXE --cov --cov-report=term-missing -vv tests

**Comment by andymaheshw** [comment]
wait sorry, the error is as follows, not sure how to set environ variables for appveyor, will look into it.
================================== FAILURES ===================================
__________________________________ test_main __________________________________
.tox\py34\lib\os.py:632: in __getitem__
    value = self._data[self.encodekey(key)]
E   KeyError: 'USER'
During handling of the above exception, another exception occurred:
tests\test_pyadobemc.py:13: in test_main
    aa = pyadobemc.AdobeAnalytics(user_name=os.environ['USER'], shared_secret=os.environ['SECRET'])
.tox\py34\lib\os.py:635: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'USER'
=========================== pytest-warning summary ==========================

**Comment by andymaheshw** [comment]
So I found the encryption method, I'll add it to appveyor.yaml.
