### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by randyzwitch** [andymaheshw/pyamc#25]
@andymaheshw Can you go into the settings page and set up GitHub Pages? Probably want to choose the option for placing the files in the `docs` directory on the master branch. If it doesn't give you that option, then you need to create the docs directory first.

**Comment by andymaheshw** [comment]
setup github pages.

**Comment by randyzwitch** [comment]
Nice. Did you set it up to use a `gh-pages` branch or `docs`?

**Comment by andymaheshw** [comment]
gh-pages

**Comment by andymaheshw** [comment]
let me know if it doesn't work...
